language: node_js
node_js: 8.9.4
script:
  - npm test;
  - npm run webpack;
  - npm run bundlesize;
  - node build-index.js my-app -f;
  - cd my-app;
  - npm test;
  - npm run webpack;
  - cd ..;
  - ./scripts/travis-install.sh
  - create-react-matt hello-world -f;
  - cd hello-world;
  - npm test;
  - npm run webpack;